DROP TABLE IF EXISTS CONSTELLATIONS;
CREATE TABLE CONSTELLATIONS(CONSTELLATION VARCHAR(255),
	START_STAR_ID INT,
	END_STAR_ID INT
);

INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',50,48);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',48,47);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',47,46);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',46,45);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',45,44);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',44,43);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Major',43,46);


INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Cassiopeia',52,51);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Cassiopeia',51,53);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Cassiopeia',53,54);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Cassiopeia',54,55);


INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',6,1);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',1,7);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',6,5);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',2,5);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',2,8);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',8,3);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',3,7);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',5,4);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Orion',4,7);


INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',9,12);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',12,13);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',13,14);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',14,18);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',14,10);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',10,11);
INSERT INTO CONSTELLATIONS (CONSTELLATION, START_STAR_ID, END_STAR_ID) VALUES('Ursa Minor',18,11);


